// Auto-generated by scripts/build-manifest.mjs
export const IMAGE_MANIFEST: Record<string, string[]> = {
  "alma": [
    "moreno_estrellas_beach-night",
    "moreno_tanga_beach-night",
    "rubio_bata_neon-room"
  ],
  "axel": [
    "cafe_ropa_studio",
    "negro_casual_car-night"
  ],
  "kira": [
    "moreno_estrellas_car-night",
    "pelirrojo_bata_studio",
    "rosa_tanga_neon-room",
    "rosa_tanga_studio"
  ],
  "liam": [
    "cafe_ropa_studio",
    "negro_casual_neon-room"
  ],
  "luna": [
    "moreno_estrellas_studio",
    "moreno_tanga_car-night",
    "moreno_toalla_neon-room",
    "pelirrojo_bata_neon-room"
  ],
  "maya": [
    "moreno_bata_studio",
    "rubio_bata_car-night",
    "rubio_tanga_car-night"
  ],
  "nia": [
    "moreno_bata_neon-room",
    "rosa_tanga_neon-room",
    "rosa_tanga_studio"
  ],
  "rin": [
    "moreno_bata_car-night",
    "moreno_casual_neon-room",
    "moreno_estrellas_beach-night",
    "moreno_tanga_studio",
    "negro_ropa_studio",
    "negro_toalla_neon-room"
  ],
  "sakura": [
    "azul_tanga_neon-room",
    "moreno_bata_car-night",
    "moreno_estrellas_beach-night",
    "moreno_tanga_studio",
    "rosa_bata_studio",
    "rosa_toalla_neon-room"
  ],
  "sasha": [
    "moreno_estrellas_neon-room",
    "moreno_tanga_neon-room",
    "pelirrojo_bata_studio",
    "rubio_estrellas_car-night"
  ],
  "vera": [
    "moreno_bata_studio",
    "pelirrojo_bata_studio",
    "pelirrojo_tanga_neon-room",
    "rubio_estrellas_car-night"
  ],
  "yuki": [
    "moreno_estrellas_neon-room",
    "moreno_toalla_neon-room",
    "rosa_bata_studio"
  ],
  "yumi": [
    "azul_bata_neon-room",
    "azul_toalla_neon-room",
    "moreno_bata_car-night",
    "moreno_estrellas_beach-night",
    "moreno_tanga_studio",
    "rosa_tanga_studio"
  ]
};
